apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-php
spec:
  maxReplicas: 7
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-php
