apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hpa-demo
  region: us-west-2
  version: "1.23"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
- name: generic-workload
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true
